models/User.php
<?php

namespace app\models;

use Yii;
use yii\base\NotSupportedException;
use yii\db\ActiveRecord;
use yii\helpers\Security;
use yii\web\IdentityInterface;
/**
 * This is the model class for table "members".
 *
 * @property integer $id
 * @property string $usernames
 * @property string $password
 * @property string $created
 * @property string $updated
 * @property string $confirm_password
 */
class User extends \yii\db\ActiveRecord implements IdentityInterface
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'usuarios';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username', 'password','confirm_password'], 'required'],
            [['creado', 'ultima_entrada'], 'safe'],
            [['username'], 'string', 'max' => 100],
            [['password'], 'compare', 'compareAttribute'=>'confirm_password'],
            [['password'], 'string', 'max' => 32],
            [['confirm_password'], 'string', 'max' => 32],
            [['username'], 'unique']
        ];
    }
    
    public function attributes()
    {
        return array_merge(
            parent::attributes(),
            ['confirm_password']
        );
    }
    
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'password' => 'Password',
            'confirm_password' => 'Confirm Password',
            'id_cargo' => 'Cargo',
            'id_adscripcion' => 'Adscripcion',
            'id_rol' => 'Rol',
            'estatus_usr' => 'Estatus',
            'ultima_entrada' => 'Ultima Entrada',
            'avatar' => 'Avatar',
        ];
    }


/** INCLUDE USER LOGIN VALIDATION FUNCTIONS**/
        /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    /**
     * @inheritdoc
     */
/* modified */
    public static function findIdentityByAccessToken($token, $type = null)
    {
          return static::findOne(['access_token' => $token]);
    }
 
    public function beforeSave($insert)
    {
        // hash new password if set
        $this->password = sha1($this->password);
        /*
        // ensure fields are null so they won't get set as empty string
        $nullAttributes = ["email", "username", "ban_time", "ban_reason"];
        foreach ($nullAttributes as $nullAttribute) {
            $this->$nullAttribute = $this->$nullAttribute ? $this->$nullAttribute : null;
        }
*/
        return parent::beforeSave($insert);
    }
    
/* removed
    public static function findIdentityByAccessToken($token)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }
*/
    /**
     * Finds user by username
     *
     * @param  string      $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username]);
    }

    /**
     * Finds user by password reset token
     *
     * @param  string      $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        $expire = \Yii::$app->params['user.passwordResetTokenExpire'];
        $parts = explode('_', $token);
        $timestamp = (int) end($parts);
        if ($timestamp + $expire < time()) {
            // token expired
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token
        ]);
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param  string  $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    { 
        return $this->password === sha1($password);
    }

    /**
     * sets encrypted password
     *
     * @param  string  $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function setHashedPassword($password)
    { 
        return $this->password = sha1($password);
    }
    
    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Security::generatePasswordHash($password);
        return true;
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Security::generateRandomKey();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Security::generateRandomKey() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }
    /** EXTENSION MOVIE **/
    
}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Usuarios;
use app\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

use yii\filters\AccessControl;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                //'only' => ['create', 'update', 'delete'],
                'only' => ['index', 'create', 'update', 'delete', 'view'],
                'rules' => [
                    [
                        'actions' => ['index', 'create', 'update', 'delete', 'view'],
                        'allow' => true,
                        'matchCallback' => function ($rule, $action) {
                            \Yii::$app->language = 'es_ES';
                            $isAdmin = \Yii::$app->user->identity->id_rol <= 2 && \Yii::$app->user->identity->estatus_usr == 1;
                            return $isAdmin;
                        }
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {   
        \Yii::$app->language = 'es_ES';
        $searchModel = new UserSearch;
        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());
        if(isset($_POST['reload']) && $_POST['reload'] == 1) {
            return $this->renderAjax('grid', [
                'dataProvider' => $dataProvider,
                'searchModel' => $searchModel,
            ]);
        } else {
            return $this->render('index', [
                'dataProvider' => $dataProvider,
                'searchModel' => $searchModel,
            ]);
        }
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id, $partial = false)
    {
        return ($partial)?$this->renderAjax('view', [
            'model' => $this->findModel($id),
        ]):$this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($partial = false)
    {        
        $model = new Usuarios;  
        $options = [
            'model' => $model,
        ];
        if ($model->load(Yii::$app->request->post())) {
            /*
            $oFile = UploadedFile::getInstance($model, 'avatar');
            if($oFile && ($oFile->extension == 'png' ||$oFile->extension == 'jpg' || $oFile->extension == 'jpeg')) {
                $model->avatar = sha1($model->username) . '.' . $oFile->extension;                
            }
             * */
             
            if(!empty($model->avatar)) {
                $uriPhp = 'data://' . substr($model->avatar, 5);
                $fp = fopen($uriPhp, 'r');
                $meta = stream_get_meta_data($fp);
                $ext = explode('/', $meta['mediatype']);
                $ext = $ext[1];
                $model->avatar = sha1($model->username) . '.' . $ext;
            } 
            
            if($model->save(true, ['username', 'password','id_cargo','id_adscripcion','id_rol','estatus_usr','avatar'])) { 
                /*if($oFile){
                    $oFile->saveAs('avatars/'.$model->avatar);
                } */
                if(!empty($model->avatar)) {
                    $binary = file_get_contents($uriPhp);
                    file_put_contents('avatars/'.$model->avatar, $binary);
                }
                return ($partial)?$model->id:$this->redirect(['view', 'id' => $model->id]); 
            } else {
                return ($partial)?$this->renderAjax('create', $options):$this->render('create', $options);
            }                       
        } else {
            return ($partial)?$this->renderAjax('create', $options):$this->render('create', $options);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id, $partial = false)
    {
        $model = $this->findModel($id);
        $options = [
            'model' => $model,
        ];
        $fields = ['username','id_cargo','id_adscripcion','id_rol','estatus_usr','avatar'];
        if ($model->load(Yii::$app->request->post())) { 
            if(!empty($model->password)){
                $fields[] = 'password';
            }
            /*
            $oFile = UploadedFile::getInstance($model, 'avatar');
            if($oFile && ($oFile->extension == 'png' ||$oFile->extension == 'jpg' || $oFile->extension == 'jpeg')) {
                $model->avatar = sha1($model->username) . '.' . $oFile->extension;                
            }*/
            
            if(!empty($model->avatar)) {
                $uriPhp = 'data://' . substr($model->avatar, 5);
                $fp = fopen($uriPhp, 'r');
                $meta = stream_get_meta_data($fp);
                $ext = explode('/', $meta['mediatype']);
                $ext = $ext[1];
                $model->avatar = sha1($model->username) . '.' . $ext;
            }            
            
            if($model->save(true, $fields)) {                
                //print_r(explode('/', $meta['mediatype'])[1]);exit;
                if(!empty($model->avatar)) {
                    $binary = file_get_contents($uriPhp);
                    file_put_contents('avatars/'.$model->avatar, $binary);
                }
                /*if($oFile){
                    $oFile->saveAs('avatars/'.$model->avatar);
                }*/
                return ($partial)?$model->id:$this->goBack(); 
            } else {
                return ($partial)?$this->renderAjax('update', $options):$this->render('update', $options);
            }  
        } else {
            return ($partial)?$this->renderAjax('update', $options):$this->render('update', $options);
        }
    }

    public function actionUpload($id) {
        echo $id; exit;
    }
    
    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        $model = Usuarios::find()
                    ->innerJoinWith('roles')
                    ->innerJoinWith('adscripciones')
                    ->innerJoinWith('nombramientos')
                    ->where(['usuarios.id'=>$id])->one();
        if ($model !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    public function actionGetkey($id)
    {   
        if($id > 0) {
            $model = $this->findModel($id);
            $oUser = $model->getAttributes();
            $keyFileSeed = Yii::$app->params['keyFileSeed'];
            $strMemberKey = sha1($keyFileSeed . $oUser['creado']);
            header("Content-disposition: attachment; filename=llave.rxt");
            header("Content-type: application/octet-stream");
            echo $strMemberKey;   
        }    
        exit;
    }
    
    public function actionMember(){
        \Yii::$app->language = 'es_ES';
        return $this->render('member', [
            'model' => $this->findModel(\Yii::$app->user->identity->id),
        ]);
    }
    
    public function actionMemberupdate(){
        \Yii::$app->language = 'es_ES';
        $model = $this->findModel(\Yii::$app->user->identity->id);
        $options = [
            'model' => $model,
        ];
        $fields = [];
        if ($model->load(Yii::$app->request->post())) { 
            if(!empty($model->password)){
                $fields[] = 'password';
            }
            if($model->save(true, $fields)) {                
                return $this->goBack();//$mode$l->id;
            } else {
                return $this->render('memberupdate', $options);
            }  
        } else {
            return $this->render('memberupdate', $options);
        }
    }
}

views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Roles;
use app\models\Nombramientos;
use app\models\Adscripciones;
use yii\helpers\ArrayHelper;
use kartik\switchinput\SwitchInput;

$this->registerCssFile(Yii::$app->urlManager->getBaseUrl() . '/css/configuracion/usuarios.css');
$this->registerJsFile(Yii::$app->homeUrl.'js/configuracion/fileReader.js', ['position' => $this::POS_END]);

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>
    <div class="left_group">
        <?= $form->field($model, 'username')->textInput(['maxlength' => 100])->label('Usuario') ?>

        <?php if(!$model->isNewRecord) {$model->password = '';} ?>
        <?= $form->field($model, 'password')->passwordInput(['maxlength' => 20]) ?>

        <?= $form->field($model, 'confirm_password')->passwordInput(['maxlength' => 20])
                ->label('Confirmar Password')
                ?>

        <?= $form->field($model, 'id_cargo')->dropDownList(
                            ArrayHelper::map(Nombramientos::find()->all(), 'id', 'grado')
                        )->label('Nombramiento');
            ?>

        <?= $form->field($model, 'id_adscripcion')->dropDownList(
                            ArrayHelper::map(Adscripciones::find()->all(), 'id', 'nombre')
                        )->label('Adscripci&oacute;n');
            ?>
        <?= $form->field($model, 'id_rol')->dropDownList(
                            ArrayHelper::map(Roles::find()->all(), 'id', 'nombre')
                        )->label('Rol');
            ?>
        <?php 
            $model->estatus_usr = $model->isNewRecord ? true:$model->estatus_usr;
            echo $form->field($model, 'estatus_usr')->checkbox(); 
            ?>
    </div>
    <div class="right_group">
        <div class='avatar_group'>
            <div class="avatar_container" id="avatar_container">
                <span>
                    <?php if($model->avatar){ ?>
                        <img class="thumb" src="<?= Yii::$app->urlManager->getBaseUrl().'/avatars/'.$model->avatar?>" title="Avatar">
                    <?php 
                        $model->avatar = '';
                    }?>                    
                </span>   
            </div>
            <div class="file_container">
                <label class="btn btn-app fotopload pull-left ui file_label">
                   <i class="glyphicon glyphicon-cloud-upload"></i>Fotografía
                   <input type="file" id="avatar_upload" class="Avatar" name="file_input" value> 
                   <?php echo $form->field($model, 'avatar',['inputOptions'=>['type' => 'hidden']])->label(false); ?>
                </label>
            </div>            
            <div class="generar_llave_cont <?= $model->isNewRecord?'no_display':'' ?>">
                <a href="<?= Yii::$app->urlManager->createUrl(['/user/getkey']).'?id='.$model->id ?>">
                    <i class="fa fa-lock"></i>
                    <div class="generar_llave">
                        Generar llave
                    </div>
                </a>
            </div>
        </div>
        <div class="form-group botones">
            <?= Html::submitButton('<i class="glyphicon glyphicon-floppy-disk"></i> Guardar', ['class' => 'btn btn-primary']) ?>
            <?= Html::button('<i class="glyphicon glyphicon-repeat"></i> Cancelar', ['class' => 'btn btn-default closer']) ?>
        </div>
    </div>
    <?php ActiveForm::end(); ?>

</div>

views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'password') ?>

    <?= $form->field($model, 'created') ?>

    <?= $form->field($model, 'updated') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Crear Usuario';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<section class="content">
    <div class="row">        
        <div class="col-md-12 main_box">
            <div class="box box-warning box-bajas user-index">
                <div class="box-header with-border">
                    <h1><?= Html::encode($this->title) ?></h1>
                    <div class="box-tools pull-right">      
                      <button type="button" class="close btn btn-box-tool" data-dismiss="modal" data-toggle="tooltip" title="Remove"><i class="fa fa-times"></i></button>
                    </div><!-- /.box-tools -->
                </div><!-- /.box-header -->
                <div class="box-body">
                    <?= $this->render('_form', [
                        'model' => $model,
                    ]) ?>
                </div><!-- /.box-body -->
            </div>    
        </div>
    </div>
</section>

views/user/grid.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
$dataProvider->pagination=['pagesize'=>10];
//$dataProvider->estatus_usr = ($dataProvider->estatus_usr)?'Si':'No';
?>
<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'tableOptions' => [
        'class' => 'table table-bordered table-hover',
    ],
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        'username',
        ['value'=>'nombramientos.grado','header'=>'Cargo'],
        ['value'=>'adscripciones.nombre','header'=>'Adscripci&oacute;n'],
        ['value'=>'roles.nombre','header'=>'Rol'],
        ['value'=>function ($model, $key, $index, $widget) {
                $return = ($model->estatus_usr == "1")?"Si":"No";
                return " " .
                $return . '';
                },'header'=>'Activo'],
        ['class' => 'yii\grid\ActionColumn'],
    ],             
    'pager' => ['prevPageLabel' => '← Anterior', 'nextPageLabel' => 'Siguiente → '],
    'layout'=>"{items}\n{summary}{pager}"
]); ?>

views/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;


$this->title = 'Usuarios';
$this->params['breadcrumbs'][] = $this->title;
$this->registerCssFile(Yii::$app->urlManager->getBaseUrl() . '/css/configuracion/config.css');
$this->registerCssFile(Yii::$app->urlManager->getBaseUrl() . '/css/configuracion/usuarios.css');
$this->registerJsFile(Yii::$app->homeUrl.'js/ajaxupload.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile(Yii::$app->homeUrl.'js/usuarios/main.js', ['position' => $this::POS_END]);

?>
<section class="content-header">

    <h1><?= Html::encode($this->title) ?></h1>

</section>
<section class="content">
    <div class="row">        
        <div class="col-md-12 main_box">
            <div class="box box-default box-bajas user-index" id="members_grid">
                <div class="box-header with-border">
                    <p>
                        <?php
                            echo Html::a('Crear Usuario',['create'], [
                            'class' => 'btn btn-success',
                            'title' => Yii::t('yii', 'Close'),
                            'onclick'=>"
                                addLoading('#members_grid');
                                $.ajax({
                               type     :'POST',
                               cache    : false,
                               url  : $(this).attr('href')+'?partial=true',
                               success  : function(response) {                                   
                                   $('#ajax_div').html(response);
                                   $('#ajaxModal').modal();
                                   endLoading('#members_grid');
                               }
                               });return false;",
                               ]);
                        ?>    
                    </p>
                    <div class="box-tools pull-right">      
                      <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
                      <button class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove"><i class="fa fa-times"></i></button>
                    </div><!-- /.box-tools -->
                </div><!-- /.box-header -->
                <div class="box-body" id="grid_cont">
                    <?php echo $this->render('grid', [
                    'dataProvider' => $dataProvider,
                    ]); ?>
                </div><!-- /.box-body -->
            </div>    
        </div>
    </div>
</section>
<!-- Modal -->
<div class="modal fade" id="ajaxModal" role="dialog" aria-labelledby="userModalLabel" aria-hidden="true" data-backdrop="false">
  <div class="modal-dialog">
    <!--<div class="modal-content">-->
      <div id="ajax_div" class="box-header">
      </div>
    <!--</div>-->    
  </div>
</div>

views/user/member.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = $model->username;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<section class="content">
    <div class="row">        
        <div class="col-md-12 main_box">
            <div class="box box-warning box-bajas user-index">
                <div class="box-header with-border">
                    <h1><?= Html::encode($this->title) ?></h1>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <?= DetailView::widget([
                        'options'=>['class' => 'table table-bordered table-hover'],
                        'model' => $model,
                        'attributes' => [
                            ['attribute'=>'username','label'=>'Usuario'],
                            ['attribute'=>'nombramientos.grado','label'=>'Cargo'],
                            ['attribute'=>'adscripciones.nombre','label'=>'Adscripci&oacute;n'],
                            ['attribute'=>'roles.nombre','label'=>'Rol'],
                            ['attribute'=>function ($model) {
                            $return = ($model->estatus_usr == "1")?"Si":"No";
                            return " " .
                            $return . '';
                            },'label'=>'Activo'],
                        ],
                    ]) ?>
                    <div class="buttoneer">
                        <?= Html::a('Actualizar Password', ['memberupdate'], ['class' => 'btn btn-primary updater']) ?>
                    </div>
                </div><!-- /.box-body -->
            </div>    
        </div>
    </div>
</section>
<!-- Modal -->
<div class="modal fade" id="ajaxModal" role="dialog" aria-labelledby="userModalLabel" aria-hidden="true" data-backdrop="false">
  <div class="modal-dialog">
    <!--<div class="modal-content">-->
      <div id="ajax_div" class="box-header">
      </div>
    <!--</div>-->    
  </div>
</div>
<style>
    .buttoneer {
        float:right;
        margin-top:10px;
    }
    .box-body {
        overflow:hidden;
    }
</style>

views/user/memberupdate.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = ''
        . 'Editar Usuario: ' . ' ' . $model->username;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<section class="content">
    <div class="row">        
        <div class="col-md-12 main_box">
            <div class="box box-warning box-bajas user-index">
                <div class="box-header with-border">
                    <h1><?= Html::encode($this->title) ?></h1>
                    <div class="box-tools pull-right">      
                      <button type="button" class="close btn btn-box-tool" data-dismiss="modal" data-toggle="tooltip" title="Remove"><i class="fa fa-times"></i></button>
                    </div><!-- /.box-tools -->
                </div><!-- /.box-header -->
                <div class="box-body">
                    <div class="user-form">
                        <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>
                        <div class="left_group">
                            <?= $form->field($model, 'username')->textInput(['maxlength' => 100, 'readonly' => true])->label('Usuario') ?>

                            <?php if(!$model->isNewRecord) {$model->password = '';} ?>

                            <?= $form->field($model, 'password')->passwordInput(['maxlength' => 20]) ?>

                            <?= $form->field($model, 'confirm_password')->passwordInput(['maxlength' => 20])
                                    ->label('Confirmar Password')
                                    ?>
                        </div>
                            <div class="form-group botones buttoneer">
                                <?= Html::submitButton('<i class="glyphicon glyphicon-floppy-disk"></i> Guardar', ['class' => 'btn btn-primary']) ?>
                                <?= Html::a('<i class="glyphicon glyphicon-repeat"></i> Cancelar', ['member'], ['class' => 'btn btn-default closer']) ?>
                            </div>
                        <?php ActiveForm::end(); ?>

                    </div>
                </div><!-- /.box-body -->
            </div>    
        </div>
    </div>
</section>
<style>
    .buttoneer {
        float:right;
        margin-top:10px;
    }
    .box-body {
        overflow:hidden;
    }
</style>

views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = ''
        . 'Editar Usuario: ' . ' ' . $model->username;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<section class="content">
    <div class="row">        
        <div class="col-md-12 main_box">
            <div class="box box-warning box-bajas user-index">
                <div class="box-header with-border">
                    <h1><?= Html::encode($this->title) ?></h1>
                    <div class="box-tools pull-right">      
                      <button type="button" class="close btn btn-box-tool" data-dismiss="modal" data-toggle="tooltip" title="Remove"><i class="fa fa-times"></i></button>
                    </div><!-- /.box-tools -->
                </div><!-- /.box-header -->
                <div class="box-body">
                    <?= $this->render('_form', [
                        'model' => $model,
                    ]) ?>
                </div><!-- /.box-body -->
            </div>    
        </div>
    </div>
</section>