models/Elementos.php
<?php

namespace app\models;

use Yii;
use yii\db\Query;

/**
 * This is the model class for table "elementos".
 */
class Elementos extends \app\models\base\Elementos
{
	const ELEMENTOS_ASPIRANTES = 1;
	const ELEMENTOS_ACTIVOS    = 2;
	const ELEMENTOS_INACTIVOS  = 3;
	const ELEMENTOS_ELIMINADOS = 4;
	const ELEMENTOS_RECHAZADOS = 5;

	public $folioConvocatoria;
	public $nombramiento;
	public $adscripcion;
	public $max_folio;
	public $nombre_estatus;
	
	/**
	 * Método para obtener todos los elementos activos con la información
	 * necesaria para la página de bajas
	 *
	 *  @return Array $arrElementos
	 */
	public function getElementosForBajas()
	{       
                $arrConditions = ['<>', 'idEstatus',self::ELEMENTOS_ASPIRANTES];
                if(\Yii::$app->user->identity->id_rol == 4) {                    
                    $arrElementos = $this->find()->where($arrConditions)->andWhere(['idTipo' => 2])->all();
                } else {
                    $arrElementos = $this->find()->where($arrConditions)->all();
                }		

		foreach ($arrElementos as $oElemento) {
			$elemento                = $this->findOne($oElemento->id);
			$oElemento->nombramiento = $elemento->getNombramientoOrderByDate();
			$oElemento->adscripcion  = $elemento->getAdscripcionOrderByDate();
		}

		return $arrElementos;
	}

	/**
	 * Metodo para realizar una busqueda de elementos activos
	 *
	 * @param String $strSearch
	 *
	 * @return Array $arrElementos
	 */
	public function searchElements ($strSearch = '')
	{
		$strQuery = "SELECT * FROM elementos WHERE ";
		$strQuery .= "idEstatus = " . self::ELEMENTOS_ACTIVOS . " AND (";
		$strQuery .= "nombre LIKE '%$strSearch%' OR ";
		$strQuery .= "apellido_paterno LIKE '%$strSearch%' OR ";
		$strQuery .= "apellido_materno LIKE '%$strSearch%' OR ";
		$strQuery .= "folio LIKE '%$strSearch%')";

		$arrElementos = $this->findBySql($strQuery)->all();

		foreach ($arrElementos as $oElemento) {	
			$elemento                = $this->findOne($oElemento->id);
			$oElemento->nombramiento = $elemento->getNombramientoOrderByDate();
			$oElemento->adscripcion  = $elemento->getAdscripcionOrderByDate();
		}

		return $arrElementos;
	}

	/**
	 * Método para obtener todos los elementos con la información
	 * necesaria para la página de personal
	 *
	 *  @return Array $arrElementos
	 */
	public function getElementosForPersonal()
	{
		$strQuery = "SELECT elm.*, est.nombre as nombre_estatus FROM elementos elm ";
		$strQuery .= "LEFT JOIN estatus est ON est.id = elm.idEstatus ";
		$strQuery .= "WHERE elm.idEstatus = " . self::ELEMENTOS_ACTIVOS;
                if(\Yii::$app->user->identity->id_rol == 4) {                    
                     $strQuery .= " AND elm.idTipo = 2 "; 
                }
                
		$arrElementos = $this->findBySql($strQuery)->all();

		foreach ($arrElementos as $oElemento) {
			$elemento                = $this->findOne($oElemento->id);
			$oElemento->nombramiento = $elemento->getNombramientoOrderByDate();
		}

		return $arrElementos;
	}

	/**
	 * Metodo para realizar una busqueda de elementos aspirantes, activos o inactivos
	 *
	 * @param String $strSearch
	 *
	 * @return Array $arrElementos
	 */
	public function searchPersonal ($strSearch = '')
	{
		$strQuery = "SELECT elm.*, est.nombre as nombre_estatus FROM elementos elm ";
		$strQuery .= "LEFT JOIN estatus est ON est.id = elm.idEstatus WHERE ";
                if(\Yii::$app->user->identity->id_rol == 4) {
                   $strQuery .= "elm.idTipo = 2 AND "; 
                }
		$strQuery .= "elm.idEstatus = " . self::ELEMENTOS_ACTIVOS . " AND (";
		$strQuery .= "elm.nombre LIKE '%$strSearch%' OR ";
		$strQuery .= "elm.apellido_paterno LIKE '%$strSearch%' OR ";
		$strQuery .= "elm.apellido_materno LIKE '%$strSearch%' OR ";
		$strQuery .= "elm.folio LIKE '%$strSearch%')";

		$arrElementos = $this->findBySql($strQuery)->all();

		foreach ($arrElementos as $oElemento) {	
			$elemento                = $this->findOne($oElemento->id);
			$oElemento->nombramiento = $elemento->getNombramientoOrderByDate();
		}

		return $arrElementos;
	}

	/**
	 * Método para obtener todos los elementos con la información
	 * necesaria para la página de historial
	 *
	 *  @return Array $arrElementos
	 */
	public function getElementosForHistorial ()
	{
		$strQuery = "SELECT elm.*, est.nombre as nombre_estatus FROM elementos elm ";
		$strQuery .= "LEFT JOIN estatus est ON est.id = elm.idEstatus ";
		$strQuery .= "WHERE elm.idEstatus = " . self::ELEMENTOS_INACTIVOS . " OR elm.idEstatus = " . self::ELEMENTOS_RECHAZADOS;

		$arrElementos = $this->findBySql($strQuery)->all();

		foreach ($arrElementos as $oElemento) {
			$elemento                = $this->findOne($oElemento->id);
			$oElemento->nombramiento = $elemento->getNombramientoOrderByDate();
		}

		return $arrElementos;
	}

	/**
	 * Metodo para realizar una busqueda de elementos aspirantes, activos o inactivos
	 *
	 * @param String $strSearch
	 *
	 * @return Array $arrElementos
	 */
	public function searchHistorial ($strSearch = '')
	{
		$strQuery = "SELECT elm.*, est.nombre as nombre_estatus FROM elementos elm ";
		$strQuery .= "LEFT JOIN estatus est ON est.id = elm.idEstatus WHERE ";
		$strQuery .= "(elm.idEstatus = " . self::ELEMENTOS_INACTIVOS . " OR elm.idEstatus = " . self::ELEMENTOS_RECHAZADOS . ") AND (";
		$strQuery .= "elm.nombre LIKE '%$strSearch%' OR ";
		$strQuery .= "elm.apellido_paterno LIKE '%$strSearch%' OR ";
		$strQuery .= "elm.apellido_materno LIKE '%$strSearch%' OR ";
		$strQuery .= "elm.folio LIKE '%$strSearch%')";

		$arrElementos = $this->findBySql($strQuery)->all();

		foreach ($arrElementos as $oElemento) {	
			$elemento                = $this->findOne($oElemento->id);
			$oElemento->nombramiento = $elemento->getNombramientoOrderByDate();
		}

		return $arrElementos;
	}

	/**
	 * Metodo para obtener todos los elementos activos para la página de reportes
	 *
	 * @return Array $arrElementos
	 */
	public function getElementosForReportes () {
		$strQuery = "SELECT clave_empleado, nombre, apellido_paterno, apellido_materno FROM elementos WHERE idEstatus = " . self::ELEMENTOS_ACTIVOS;

		$arrElementos = $this->findBySql($strQuery)->all();

		return $arrElementos;
	}

	public function findAspirantes() {
                $arrConditions = ['idEstatus' => 1];
                if(\Yii::$app->user->identity->id_rol == 4) {                    
                     $arrConditions['idTipo'] = 2; 
                }
		$arrElementos = $this->find()
			->select('elementos.*, convocatorias.folio as folioConvocatoria')
			->joinWith('idConvocatoria0')
			->where($arrConditions)
			->all();
		return $arrElementos;
	}

	public function reasignarRequerimientos($idElemento) {
		$db = Yii::$app->getDb();
    	$db->createCommand("update elementos set idEtapa=:idEtapa where id=:idElemento")
    	   ->bindValue(':idElemento', $idElemento)
    	   ->bindValue(':idEtapa', $idEtapa)
    	   ->execute();
    	return true;
	}

	public function setEtapa($idElemento, $idEtapa) {
		/*$strQuery = "CALL inserta_requerimientos(:idElemento)";
		$arrElementos = $this->findBySql($strQuery)->all();*/
    	$db = Yii::$app->getDb();
    	$db->createCommand("update elementos set idEtapa=:idEtapa where id=:idElemento")
    	   ->bindValue(':idElemento', $idElemento)
    	   ->bindValue(':idEtapa', $idEtapa)
    	   ->execute();
    	return true;
	}

	public function getFechaIngresoText() {
		return date('d/m/Y', strtotime($this->fecha_ingreso));
	}

	public function findActivos() {
                $arrConditions = ['idEstatus' => self::ELEMENTOS_ACTIVOS];
                if(\Yii::$app->user->identity->id_rol == 4) {                    
                     $arrConditions['idTipo'] = 2; 
                }
		$arrElementos = $this->find()
			->where($arrConditions)
			->all();
		return $arrElementos;
	}

	public function searchAspirantes($search = '') {
                
		$query = "select e.id, ";
		$query .= "concat(e.nombre, ' ', e.apellido_paterno, ' ', e.apellido_materno) as nombre,";
		$query .= "e.folio, c.folio as folioConvocatoria";
		$query .= " from elementos as e, convocatorias as c";
		$query .= " where e.idEstatus = 1";
		$query .= " and e.idConvocatoria = c.id";
		$query .= " and (e.nombre like '%$search%'";
                if(\Yii::$app->user->identity->id_rol == 4) {
                   $query .= " and e.idTipo = 2"; 
                }
		$query .= " or e.folio like '%$search%'";
		$query .= " or c.folio like '%$search%')"; 
		$arrElementos = $this->findBySql($query)->all();
		return $arrElementos;
	}

	public function searchActivos($search = '') {
		$strQuery = "SELECT * FROM elementos WHERE ";
                if(\Yii::$app->user->identity->id_rol == 4) {
                   $strQuery .= "idTipo = 2 AND "; 
                }
		$strQuery .= "idEstatus = " . self::ELEMENTOS_ACTIVOS . " AND (";
		$strQuery .= "nombre LIKE '%$search%' OR ";
		$strQuery .= "apellido_paterno LIKE '%$search%' OR ";
		$strQuery .= "apellido_materno LIKE '%$search%' OR ";
		$strQuery .= "clave_empleado LIKE '%$search%')";

		$arrElementos = $this->findBySql($strQuery)->all();
		return $arrElementos;
	}

	public static function findLogCursos($idElemento) {
		return Elementos::findOne($idElemento)->getLogCursos()->all();
	}

	public function getNombreText() {
		return $this->nombre . ' ' . $this->apellido_paterno . ' ' . $this->apellido_materno;
	}

	/**
	 * Método para obtener el ultimo nombramiento (por fecha) asignado a un elemento
	 *
	 * @return Object
	 */
	public function getNombramientoOrderByDate()
	{
		$lastLog = $this->getLogNombramientos()->orderBy(['fecha' => SORT_DESC])->limit(1)->one();

models/Nombramientos.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "nombramientos".
 */
class Nombramientos extends \app\models\base\Nombramientos
{
}

controllers/NombramientosController.php
<?php

namespace app\controllers;

use app\models\nombramientos;
use app\models\nombramientosSearch;
use app\models\Elementos;
use app\models\FormSearch;
use Yii;
use yii\web\Controller;
use yii\web\HttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\helpers\Html;

/**
 * NombramientosController implements the CRUD actions for nombramientos model.
 */
class NombramientosController extends Controller
{
	/**
	 * Lists all nombramientos models.
	 * @return mixed
	 */
	public function actionIndex()
	{
            
            $model     = new Elementos();
            $form      = new FormSearch();
            $elementos = null;
            $search    = null;

            if ($form->load(Yii::$app->request->post())) {
                    $search    = Html::encode($form->search_element);
                    $elementos = $model->searchActivos($search);
            } else {
                $elementos = $model->findActivos();
            }                
            Url::remember();
            return $this->render('index', [
                'elementos' => $elementos,
                'form' => $form,
                'search' => $search
            ]);
            
            
            
            $searchModel = new nombramientosSearch;
            $dataProvider = $searchModel->search($_GET);

            Url::remember();
            return $this->render('index', [
                    'dataProvider' => $dataProvider,
                    'searchModel' => $searchModel,
            ]);
	}

	/**
	 * Displays a single nombramientos model.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionView($id)
	{
        Url::remember();
        return $this->render('view', [
			'model' => $this->findModel($id),
		]);
	}

	/**
	 * Creates a new nombramientos model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 * @return mixed
	 */
	public function actionCreate()
	{
		$model = new nombramientos;

		try {
            if ($model->load($_POST) && $model->save()) {
                return $this->redirect(Url::previous());
            } elseif (!\Yii::$app->request->isPost) {
                $model->load($_GET);
            }
        } catch (\Exception $e) {
            $msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
            $model->addError('_exception', $msg);
		}
        return $this->render('create', ['model' => $model,]);
	}

	/**
	 * Updates an existing nombramientos model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionUpdate($id)
	{
		$model = $this->findModel($id);

		if ($model->load($_POST) && $model->save()) {
            return $this->redirect(Url::previous());
		} else {
			return $this->render('update', [
				'model' => $model,
			]);
		}
	}

	/**
	 * Deletes an existing nombramientos model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionDelete($id)
	{
		$this->findModel($id)->delete();
		return $this->redirect(Url::previous());
	}

	/**
	 * Finds the nombramientos model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 * @param integer $id
	 * @return nombramientos the loaded model
	 * @throws HttpException if the model cannot be found
	 */
	protected function findModel($id)
	{
		if (($model = nombramientos::findOne($id)) !== null) {
			return $model;
		} else {
			throw new HttpException(404, 'The requested page does not exist.');
		}
	}
}

views/nombramientos/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/**
* @var yii\web\View $this
* @var app\models\nombramientos $model
* @var yii\widgets\ActiveForm $form
*/
?>

<div class="nombramientos-form">

    <?php $form = ActiveForm::begin(['layout' => 'horizontal', 'enableClientValidation' => false]); ?>

    <div class="">
        <?php echo $form->errorSummary($model); ?>
        <?php $this->beginBlock('main'); ?>

        <p>
            
			<?= $form->field($model, 'grado')->textInput(['maxlength' => 45]) ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    \yii\bootstrap\Tabs::widget(
                 [
                   'encodeLabels' => false,
                     'items' => [ [
    'label'   => 'Nombramientos',
    'content' => $this->blocks['main'],
    'active'  => true,
], ]
                 ]
    );
    ?>
        <hr/>

        <?= Html::submitButton('<span class="glyphicon glyphicon-check"></span> '.($model->isNewRecord ? 'Create' : 'Save'), ['class' => $model->isNewRecord ?
        'btn btn-primary' : 'btn btn-primary']) ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

views/nombramientos/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var app\models\nombramientosSearch $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="nombramientos-search">

	<?php $form = ActiveForm::begin([
		'action' => ['index'],
		'method' => 'get',
	]); ?>

		<?= $form->field($model, 'id') ?>

		<?= $form->field($model, 'grado') ?>

		<div class="form-group">
			<?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
			<?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
		</div>

	<?php ActiveForm::end(); ?>

</div>

views/nombramientos/create.php
<?php

use yii\helpers\Html;

/**
* @var yii\web\View $this
* @var app\models\nombramientos $model
*/

$this->title = 'Create';
$this->params['breadcrumbs'][] = ['label' => 'Nombramientos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="nombramientos-create">

    <p class="pull-left">
        <?= Html::a('Cancel', \yii\helpers\Url::previous(), ['class' => 'btn btn-default']) ?>
    </p>
    <div class="clearfix"></div>

    <?php echo $this->render('_form', [
    'model' => $model,
    ]); ?>

</div>

views/nombramientos/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
$this->registerJsFile(Yii::$app->homeUrl.'js/datatables/tablas.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerCssFile(Yii::$app->homeUrl . '/css/activos/planes.css');
$urlIndex = Url::to(['nombramientos/']);
$this->title = 'Nombramientos';
?>

<section class="content-header">

    <h1>
        <?php echo $this->title; ?>
        <small></small>
    </h1>

    <ol class="breadcrumb">
        <li><a href="<?php echo Yii::$app->homeUrl; ?>"><i class="fa fa-home"></i> Inicio</a></li>
        <li class="active"><?php echo $this->title; ?></li>
    </ol>

</section>

<section class="content">
    <div class="box box-primary">
        <div class="box-header">
            <div class="col-md-6 col-md-offset-2 search-box">
                <?php
                    $f = ActiveForm::begin([
                        'action'                 => $urlIndex,
                        'method'                 => 'post',
                        'enableClientValidation' => false
                    ]);
                ?>

                <?= $this->render('//layouts/search_submit', []); ?>
                <?php ActiveForm::end(); ?>
            </div>
        </div>

        <div class="box-body">
            <div id="ajax-content" class="box">
                <div class="bg-navy-active">
                    <h5>Resultados de la búsqueda</h5>
                </div>
                <table id="resultados" class="table table-bordered table-hover table-striped">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Número de empleado</th>
                            <th>Nombre del elemento</th>
                            <th>Nombramiento</th>
                            <th>Adscripción</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if (count($elementos) > 0) { ?>
                        <?php $contador = 1; ?>
                            <?php foreach ( $elementos as $elemento ) { ?>
                                <tr>
                                    <td><?php echo $contador++; ?></td>
                                    <td><?php echo $elemento->clave_empleado; ?></td>
                                    <td><?php echo $elemento->nombreText; ?></td>
                                    <td><?php echo $elemento->getNombramiento()->grado; ?></td>
                                    <td><?php echo $elemento->getAdscripcion()->nombre; ?></td>
                                    <td>
                                        <a class="btn btn-block" href="<?php echo Url::to(['log-nombramientos/', 'id' => $elemento->id]); ?>">
                                            <span data-toggle="tooltip" data-placement="left" title="Ver" class="glyphicon glyphicon-eye-open"></span>
                                        </a>
                                    </td>
                                </tr>
                            <?php } ?>
                        <?php } ?>
                    </tbody>
                    <tfoot>
                    </tfoot>
                </table>
            </div>
        </div>

        <div class="box-footer">
        </div>

    </div>
</section>

views/nombramientos/update.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\models\nombramientos $model
 */

$this->title = 'Nombramientos Update ' . $model->id . '';
$this->params['breadcrumbs'][] = ['label' => 'Nombramientos', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Edit';
?>
<div class="nombramientos-update">

    <p>
        <?= Html::a('<span class="glyphicon glyphicon-eye-open"></span> View', ['view', 'id' => $model->id], ['class' => 'btn btn-info']) ?>
    </p>

	<?php echo $this->render('_form', [
		'model' => $model,
	]); ?>

</div>

views/nombramientos/view.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;

/**
* @var yii\web\View $this
* @var app\models\nombramientos $model
*/

$this->title = 'Nombramientos View ' . $model->id . '';
$this->params['breadcrumbs'][] = ['label' => 'Nombramientos', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="nombramientos-view">

    <p class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> Edit', ['update', 'id' => $model->id],
        ['class' => 'btn btn-info']) ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> New Nombramientos', ['create'], ['class' => 'btn
        btn-success']) ?>
    </p>

        <p class='pull-right'>
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> List', ['index'], ['class'=>'btn btn-default']) ?>
    </p><div class='clearfix'></div> 

    
    <h3>
        <?= $model->id ?>    </h3>


    <?php $this->beginBlock('app\models\nombramientos'); ?>

    <?php echo DetailView::widget([
    'model' => $model,
    'attributes' => [
    			'id',
			'grado',
    ],
    ]); ?>

    <hr/>

    <?php echo Html::a('<span class="glyphicon glyphicon-trash"></span> Delete', ['delete', 'id' => $model->id],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => Yii::t('app', 'Are you sure to delete this item?'),
    'data-method' => 'post',
    ]); ?>

    <?php $this->endBlock(); ?>


    
<?php $this->beginBlock('LogNombramientos'); ?>
<p class='pull-right'>
  <?= \yii\helpers\Html::a(
            '<span class="glyphicon glyphicon-list"></span> List All Log Nombramientos',
            ['log-nombramientos/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= \yii\helpers\Html::a(
            '<span class="glyphicon glyphicon-plus"></span> New Log Nombramiento',
            ['log-nombramientos/create', 'LogNombramiento'=>['idTipo'=>$model->id]],
            ['class'=>'btn btn-success btn-xs']
        ) ?>
</p><div class='clearfix'></div>
<?php $this->endBlock() ?>


    <?=
    \yii\bootstrap\Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [ [
    'label'   => '<span class="glyphicon glyphicon-asterisk"></span> nombramientos',
    'content' => $this->blocks['app\models\nombramientos'],
    'active'  => true,
],[
    'label'   => '<small><span class="glyphicon glyphicon-paperclip"></span> Log Nombramientos</small>',
    'content' => $this->blocks['LogNombramientos'],
    'active'  => false,
], ]
                 ]
    );
    ?></div>