models/Cursos.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "cursos".
 */
class Cursos extends \app\models\base\Cursos
{
	public function getDuracionText() {
		return $this->duracion . ' horas';
	}

	public function getObligatorioText() {
		return $this->obligatorio ? 'obligatorio' : 'opcional';
	}
}

models/Elementos.php
<?php

namespace app\models;

use Yii;
use yii\db\Query;

/**
 * This is the model class for table "elementos".
 */
class Elementos extends \app\models\base\Elementos
{
	const ELEMENTOS_ASPIRANTES = 1;
	const ELEMENTOS_ACTIVOS    = 2;
	const ELEMENTOS_INACTIVOS  = 3;
	const ELEMENTOS_ELIMINADOS = 4;
	const ELEMENTOS_RECHAZADOS = 5;

	public $folioConvocatoria;
	public $nombramiento;
	public $adscripcion;
	public $max_folio;
	public $nombre_estatus;
	
	/**
	 * Método para obtener todos los elementos activos con la información
	 * necesaria para la página de bajas
	 *
	 *  @return Array $arrElementos
	 */
	public function getElementosForBajas()
	{       
                $arrConditions = ['<>', 'idEstatus',self::ELEMENTOS_ASPIRANTES];
                if(\Yii::$app->user->identity->id_rol == 4) {                    
                    $arrElementos = $this->find()->where($arrConditions)->andWhere(['idTipo' => 2])->all();
                } else {
                    $arrElementos = $this->find()->where($arrConditions)->all();
                }		

		foreach ($arrElementos as $oElemento) {
			$elemento                = $this->findOne($oElemento->id);
			$oElemento->nombramiento = $elemento->getNombramientoOrderByDate();
			$oElemento->adscripcion  = $elemento->getAdscripcionOrderByDate();
		}

		return $arrElementos;
	}

	/**
	 * Metodo para realizar una busqueda de elementos activos
	 *
	 * @param String $strSearch
	 *
	 * @return Array $arrElementos
	 */
	public function searchElements ($strSearch = '')
	{
		$strQuery = "SELECT * FROM elementos WHERE ";
		$strQuery .= "idEstatus = " . self::ELEMENTOS_ACTIVOS . " AND (";
		$strQuery .= "nombre LIKE '%$strSearch%' OR ";
		$strQuery .= "apellido_paterno LIKE '%$strSearch%' OR ";
		$strQuery .= "apellido_materno LIKE '%$strSearch%' OR ";
		$strQuery .= "folio LIKE '%$strSearch%')";

		$arrElementos = $this->findBySql($strQuery)->all();

		foreach ($arrElementos as $oElemento) {	
			$elemento                = $this->findOne($oElemento->id);
			$oElemento->nombramiento = $elemento->getNombramientoOrderByDate();
			$oElemento->adscripcion  = $elemento->getAdscripcionOrderByDate();
		}

		return $arrElementos;
	}

	/**
	 * Método para obtener todos los elementos con la información
	 * necesaria para la página de personal
	 *
	 *  @return Array $arrElementos
	 */
	public function getElementosForPersonal()
	{
		$strQuery = "SELECT elm.*, est.nombre as nombre_estatus FROM elementos elm ";
		$strQuery .= "LEFT JOIN estatus est ON est.id = elm.idEstatus ";
		$strQuery .= "WHERE elm.idEstatus = " . self::ELEMENTOS_ACTIVOS;
                if(\Yii::$app->user->identity->id_rol == 4) {                    
                     $strQuery .= " AND elm.idTipo = 2 "; 
                }
                
		$arrElementos = $this->findBySql($strQuery)->all();

		foreach ($arrElementos as $oElemento) {
			$elemento                = $this->findOne($oElemento->id);
			$oElemento->nombramiento = $elemento->getNombramientoOrderByDate();
		}

		return $arrElementos;
	}

	/**
	 * Metodo para realizar una busqueda de elementos aspirantes, activos o inactivos
	 *
	 * @param String $strSearch
	 *
	 * @return Array $arrElementos
	 */
	public function searchPersonal ($strSearch = '')
	{
		$strQuery = "SELECT elm.*, est.nombre as nombre_estatus FROM elementos elm ";
		$strQuery .= "LEFT JOIN estatus est ON est.id = elm.idEstatus WHERE ";
                if(\Yii::$app->user->identity->id_rol == 4) {
                   $strQuery .= "elm.idTipo = 2 AND "; 
                }
		$strQuery .= "elm.idEstatus = " . self::ELEMENTOS_ACTIVOS . " AND (";
		$strQuery .= "elm.nombre LIKE '%$strSearch%' OR ";
		$strQuery .= "elm.apellido_paterno LIKE '%$strSearch%' OR ";
		$strQuery .= "elm.apellido_materno LIKE '%$strSearch%' OR ";
		$strQuery .= "elm.folio LIKE '%$strSearch%')";

		$arrElementos = $this->findBySql($strQuery)->all();

		foreach ($arrElementos as $oElemento) {	
			$elemento                = $this->findOne($oElemento->id);
			$oElemento->nombramiento = $elemento->getNombramientoOrderByDate();
		}

		return $arrElementos;
	}

	/**
	 * Método para obtener todos los elementos con la información
	 * necesaria para la página de historial
	 *
	 *  @return Array $arrElementos
	 */
	public function getElementosForHistorial ()
	{
		$strQuery = "SELECT elm.*, est.nombre as nombre_estatus FROM elementos elm ";
		$strQuery .= "LEFT JOIN estatus est ON est.id = elm.idEstatus ";
		$strQuery .= "WHERE elm.idEstatus = " . self::ELEMENTOS_INACTIVOS . " OR elm.idEstatus = " . self::ELEMENTOS_RECHAZADOS;

		$arrElementos = $this->findBySql($strQuery)->all();

		foreach ($arrElementos as $oElemento) {
			$elemento                = $this->findOne($oElemento->id);
			$oElemento->nombramiento = $elemento->getNombramientoOrderByDate();
		}

		return $arrElementos;
	}

	/**
	 * Metodo para realizar una busqueda de elementos aspirantes, activos o inactivos
	 *
	 * @param String $strSearch
	 *
	 * @return Array $arrElementos
	 */
	public function searchHistorial ($strSearch = '')
	{
		$strQuery = "SELECT elm.*, est.nombre as nombre_estatus FROM elementos elm ";
		$strQuery .= "LEFT JOIN estatus est ON est.id = elm.idEstatus WHERE ";
		$strQuery .= "(elm.idEstatus = " . self::ELEMENTOS_INACTIVOS . " OR elm.idEstatus = " . self::ELEMENTOS_RECHAZADOS . ") AND (";
		$strQuery .= "elm.nombre LIKE '%$strSearch%' OR ";
		$strQuery .= "elm.apellido_paterno LIKE '%$strSearch%' OR ";
		$strQuery .= "elm.apellido_materno LIKE '%$strSearch%' OR ";
		$strQuery .= "elm.folio LIKE '%$strSearch%')";

		$arrElementos = $this->findBySql($strQuery)->all();

		foreach ($arrElementos as $oElemento) {	
			$elemento                = $this->findOne($oElemento->id);
			$oElemento->nombramiento = $elemento->getNombramientoOrderByDate();
		}

		return $arrElementos;
	}

	/**
	 * Metodo para obtener todos los elementos activos para la página de reportes
	 *
	 * @return Array $arrElementos
	 */
	public function getElementosForReportes () {
		$strQuery = "SELECT clave_empleado, nombre, apellido_paterno, apellido_materno FROM elementos WHERE idEstatus = " . self::ELEMENTOS_ACTIVOS;

		$arrElementos = $this->findBySql($strQuery)->all();

		return $arrElementos;
	}

	public function findAspirantes() {
                $arrConditions = ['idEstatus' => 1];
                if(\Yii::$app->user->identity->id_rol == 4) {                    
                     $arrConditions['idTipo'] = 2; 
                }
		$arrElementos = $this->find()
			->select('elementos.*, convocatorias.folio as folioConvocatoria')
			->joinWith('idConvocatoria0')
			->where($arrConditions)
			->all();
		return $arrElementos;
	}

	public function reasignarRequerimientos($idElemento) {
		$db = Yii::$app->getDb();
    	$db->createCommand("update elementos set idEtapa=:idEtapa where id=:idElemento")
    	   ->bindValue(':idElemento', $idElemento)
    	   ->bindValue(':idEtapa', $idEtapa)
    	   ->execute();
    	return true;
	}

	public function setEtapa($idElemento, $idEtapa) {
		/*$strQuery = "CALL inserta_requerimientos(:idElemento)";
		$arrElementos = $this->findBySql($strQuery)->all();*/
    	$db = Yii::$app->getDb();
    	$db->createCommand("update elementos set idEtapa=:idEtapa where id=:idElemento")
    	   ->bindValue(':idElemento', $idElemento)
    	   ->bindValue(':idEtapa', $idEtapa)
    	   ->execute();
    	return true;
	}

	public function getFechaIngresoText() {
		return date('d/m/Y', strtotime($this->fecha_ingreso));
	}

	public function findActivos() {
                $arrConditions = ['idEstatus' => self::ELEMENTOS_ACTIVOS];
                if(\Yii::$app->user->identity->id_rol == 4) {                    
                     $arrConditions['idTipo'] = 2; 
                }
		$arrElementos = $this->find()
			->where($arrConditions)
			->all();
		return $arrElementos;
	}

	public function searchAspirantes($search = '') {
                
		$query = "select e.id, ";
		$query .= "concat(e.nombre, ' ', e.apellido_paterno, ' ', e.apellido_materno) as nombre,";
		$query .= "e.folio, c.folio as folioConvocatoria";
		$query .= " from elementos as e, convocatorias as c";
		$query .= " where e.idEstatus = 1";
		$query .= " and e.idConvocatoria = c.id";
		$query .= " and (e.nombre like '%$search%'";
                if(\Yii::$app->user->identity->id_rol == 4) {
                   $query .= " and e.idTipo = 2"; 
                }
		$query .= " or e.folio like '%$search%'";
		$query .= " or c.folio like '%$search%')"; 
		$arrElementos = $this->findBySql($query)->all();
		return $arrElementos;
	}

	public function searchActivos($search = '') {
		$strQuery = "SELECT * FROM elementos WHERE ";
                if(\Yii::$app->user->identity->id_rol == 4) {
                   $strQuery .= "idTipo = 2 AND "; 
                }
		$strQuery .= "idEstatus = " . self::ELEMENTOS_ACTIVOS . " AND (";
		$strQuery .= "nombre LIKE '%$search%' OR ";
		$strQuery .= "apellido_paterno LIKE '%$search%' OR ";
		$strQuery .= "apellido_materno LIKE '%$search%' OR ";
		$strQuery .= "clave_empleado LIKE '%$search%')";

		$arrElementos = $this->findBySql($strQuery)->all();
		return $arrElementos;
	}

	public static function findLogCursos($idElemento) {
		return Elementos::findOne($idElemento)->getLogCursos()->all();
	}

	public function getNombreText() {
		return $this->nombre . ' ' . $this->apellido_paterno . ' ' . $this->apellido_materno;
	}

	/**
	 * Método para obtener el ultimo nombramiento (por fecha) asignado a un elemento
	 *
	 * @return Object
	 */
	public function getNombramientoOrderByDate()
	{
		$lastLog = $this->getLogNombramientos()->orderBy(['fecha' => SORT_DESC])->limit(1)->one();

models/LogCursos.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "log_cursos".
 */
class LogCursos extends \app\models\base\LogCursos
{
	const ETAPA_ACTIVO = 6;

	public $nombre_curso;
	public $duracion_curso;
	public $obligatorio_curso;

    public function getCurso() {
		return $this->hasOne(Cursos::className(), ['id' => 'idCurso']);
	}

	public function getCumplimientoText() {
		return $this->cumplimiento ? 'Si' : 'No';
	}

	public function getFechaText() {
		return date('d/m/Y', strtotime($this->fecha));
	}
        
	public function getFechaFinText() {
		return date('d/m/Y', strtotime($this->fecha_fin));
	}

	public function getDuracionText() {
		return $this->duracion_curso . ' horas';
	}

	public function getObligatorioText() {
		return $this->obligatorio_curso ? 'obligatorio' : 'opcional';
	}

	/**
     * Función para obtener todos los cursos en la etapa Activo
     */
    public function getLogCursosByElementoAndEtapa($numElementoId)
    {
    	$strQuery = "SELECT ";
    	$strQuery .= "lcursos.id, cur.nombre AS nombre_curso, cur.duracion AS duracion_curso, ";
    	$strQuery .= "cur.obligatorio AS obligatorio_curso, lcursos.cumplimiento, ";
    	$strQuery .= "lcursos.calificacion, lcursos.fecha, lcursos.fecha_fin ";
		$strQuery .= "FROM log_cursos lcursos ";
		$strQuery .= "LEFT JOIN cursos cur ON lcursos.idCurso = cur.id ";
		$strQuery .= "WHERE lcursos.idElemento = " . $numElementoId . " AND cur.idEtapa = " . self::ETAPA_ACTIVO;
                
		$arrCursos = $this->findBySql($strQuery)->all();

        return $arrCursos;
    }
}

views/aspirantes/form_formacion.php
<?php 
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Cursos;
use app\models\LogCursos;
$this->registerJsFile(Yii::$app->homeUrl.'js/main/modals.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
//$this->registerJsFile(Yii::$app->homeUrl.'js/datatables/tablas.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
$blockName = 'formacion';
?>
<div class="row">
	
    <div class="col-xs-2 pull-right">
        <a class="btn btn-app" data-toggle="modal" data-target="#next-nombramiento" <?= (($aspirante->reprobadoFormacionInicial() > 0) || ($aspirante->idEtapa > 4) || ($aspirante->promedioFormacionInicial() < 8)) ? 'disabled' : '' ?>>
            <i data-toggle="tooltip" data-placement="left" title="Siguiente etapa" class="glyphicon glyphicon-ok-sign"></i>Etapa Validada
        </a>
    </div>
    <div class="col-xs-2 pull-right">
	    <a class="btn btn-app" data-toggle="modal" data-target="#modal-rechazar3">
	        <i data-toggle="tooltip" data-placement="left" title="Rechazar elemento" class="glyphicon glyphicon-ban-circle"></i>Rechazar Elemento
	    </a>
	</div>
</div>
<div class="">
	<div class="bg-navy-active">
		<h5>Agregar nuevo curso al expediente del aspirante</h5>
	</div>
	<?php $form = ActiveForm::begin([
		'action' => Url::to(['aspirantes-formacion/create']),
		'method' => 'post',
		'enableClientValidation' => false]);
	?>
	<div class="row">
		<?php echo $form->errorSummary($logCursos); ?>
	</div>
	<div class="row">
		<?php $this->beginBlock($blockName); ?>
		<div class="col-md-2">
			<?= $form->field($logCursos, 'idCurso')
				->label('Nombre del curso')
		        ->dropDownList(
		        	ArrayHelper::map(Cursos::find()->where('idEtapa=4')->all(), 'id', 'nombre'),
		        	['prompt' => '--cursos--']
		        )
	        ?>
		</div>
		<div class="col-md-2">
			<?= $form->field($logCursos, 'calificacion')->textInput(['type'=>'number', 'max'=>'10', 'step'=>'0.01']); ?>
		</div>
		<div class="col-md-3">
			<?= $form->field($logCursos, 'fecha')->textInput(['type' => 'date']); ?>
		</div>
		<div class="col-md-3">
			<?= $form->field($logCursos, 'fecha_fin')->textInput(['type' => 'date']); ?>
		</div>
		<div class="col-md-3">
			<?= $form->field($logCursos, 'observaciones')->textarea(); ?>
		</div>
		<div class="col-md-2">
			<label class="control-label"></label>
			<span class="">
				<?php echo Html::submitButton('', ['class' => 'btn btn-info btn-block fa fa-plus-circle']); ?>
			</span>
			<?= $form->field($logCursos, 'idElemento')->label(false)->textInput(['type' => 'hidden', 'value' => $aspirante->id]); ?>
			<?= $form->field($logCursos, 'cumplimiento')->label(false)->textInput(['type' => 'hidden', 'value' => 1]); ?>
		</div>
		<?php $this->endBlock(); ?>
		<?php ActiveForm::end(); ?>
		<p>
			<?= $this->blocks[$blockName]; ?>
		</p>
	</div>
	<div class="bg-navy-active">
		<h5>Histórico de formación continua</h5>
	</div>
	<?php
		if ($aspirante->promedioFormacionInicial() > 8) {
	?>
			<button class="btn bg-olive btn-flat margin pull-right">Promedio: <?= number_format($aspirante->promedioFormacionInicial(), 2, '.', ''); ?></button>
	<?php
		} elseif ($aspirante->promedioFormacionInicial() == 8) {
	?>
			<button class="btn bg-orange btn-flat margin pull-right">Promedio: <?= number_format($aspirante->promedioFormacionInicial(), 2, '.', ''); ?></button>
	<?php
		} else {
	?>
			<button class="btn bg-red btn-flat margin pull-right">Promedio: <?= number_format($aspirante->promedioFormacionInicial(), 2, '.', ''); ?></button>
	<?php
		}
	?>
	<table id="resultados" class="table table-bordered table-hover">
		<thead>
			<tr>
				<th>No</th>
				<th>Nombre del curso</th>
				<th>Duracion</th>
				<th>Importancia</th>
				<th>Calificacion</th>
				<th>Fecha</th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<?php if (count($aspirante->logCursos) > 0) { ?>
				<?php $contador = 1; ?>
				<?php foreach ( $aspirante->logCursos as $logCurso ) { ?>
					<tr>
						<td><?php echo $contador++; ?></td>
						<td><?php echo $logCurso->curso->nombre; ?></td>
						<td><?php echo $logCurso->curso->duracionText ?></td>
						<td><?php echo $logCurso->curso->obligatorioText; ?></td>
						<td><?php echo $logCurso->calificacion; ?></td>
						<td><?php echo $logCurso->fechaText; ?></td>
						<td>
							<a class="btn btn-block" data-toggle="modal" data-target="#modal-model" data-modal-type="edit" data-action="<?php echo Url::to(['aspirantes-formacion/update', 'id' => $logCurso->id]) ?>">
								<span data-toggle="tooltip" data-placement="left" title="Editar" class="glyphicon glyphicon-pencil"></span>
							</a>
						</td>
						<td>
							<a class="btn btn-block" data-toggle="modal" data-target="#modal-model" data-modal-type="remove" data-action="<?php echo Url::to(['aspirantes-formacion/delete', 'id' => $logCurso->id]) ?>">
								<span data-toggle="tooltip" data-placement="left" title="Eliminar" class="glyphicon glyphicon-trash"></span>
							</a>
						</td>
					</tr>
				<?php } ?>
			<?php } ?>
		</tbody>
		<tfoot>
        </tfoot>
	</table>
</div>
<?= $this->render('@app/views/layouts/modal', []); ?>

<div class="modal fade" id="next-nombramiento" tabindex="-1" role="dialog" aria-labelledby="next-nombramiento" aria-hidden="true">
    <div class="modal-dialog">
        <?php 
            $form = ActiveForm::begin([
                'layout' => 'horizontal',
                'enableClientValidation' => false,
                'action'=>Yii::$app->homeUrl . 'aspirantes/habilita-nombramiento?id=' . $aspirante->id,
                'id'=>'next-nombramiento',
                'method'=>'post'
            ]);
        ?>
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Habilitar Nombramiento</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="form-group col-xs-11">
                        <h5>Se habilitará la siguiente etapa de captura para el aspirante <?= $aspirante->nombre . ' ' . $aspirante->apellido_paterno . ' ' . $aspirante->apellido_materno ?>, ¿Desea continuar?</n5>
                        <div class="col-sm-6">
                            <?= $form->field($aspirante, 'id')
                                     ->textInput(['type'=>'hidden'])
                                     ->label(false); ?>
                        </div>
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary modal-input">SI</button>
                <button class="btn btn-default modal-input" data-dismiss="modal">NO</button>
            </div>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

<div class="modal fade" id="modal-rechazar3" tabindex="-1" role="dialog" aria-labelledby="modal-rechazar2" aria-hidden="true">
    <div class="modal-dialog">
        <?php 
            $form = ActiveForm::begin([
                'layout' => 'horizontal',
                'enableClientValidation' => false,
                'action'=>Yii::$app->homeUrl . 'aspirantes/rechazar-aspirante?id=' . $aspirante->id,
                'id'=>'next-seleccion',
                'method'=>'post'
            ]);
        ?>
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Rechazar Elemento</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="form-group col-xs-11">
                        <p>
                            El estatus del aspirante <?= $aspirante->nombre . ' ' . $aspirante->apellido_paterno . ' ' . $aspirante->apellido_materno ?> cambiará a RECHAZADO, ¿Desea continuar?
                        </p>
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary modal-input">SI</button>
                <button class="btn btn-default modal-input" data-dismiss="modal">NO</button>
            </div>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

views/aspirantes/form_seleccion.php
<?php 
    use yii\bootstrap\ActiveForm;
    use app\models\LogRequerimientos;
    use app\models\Requerimientos;
    use app\models\ResultadosSeleccion;
    use yii\helpers\Url;
    use yii\helpers\Html;
    use yii\helpers\ArrayHelper;

    /* @var $this yii\web\View */
    $blockName = 'reclutamiento';
?>

<div class="row">
    <div class="bg-navy-active">
        <h5>Posibles Resultados de las Evaluaciones</h5>
    </div>
</div>
<table id="tabla-resultados" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Concepto</th>
            <th>Descripcion</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                Apto y/o Recomendable
            </td>
            <td>
                Aquel que refleja los resultados satisfactorios a los requerimientos de la totalidad de los exámenes de esta evaluación.
            </td>
        </tr>
        <tr>
            <td>
                Recomendable con Reservas
            </td>
            <td>
                Aquel que cumple con los parámetros de cualquiera de los exámenes, pero que existen características específicas, que deben marcarse y tomarse en cuenta para las actividades a desarrollar dentro de la corporación.
            </td>
        </tr>
        
        <tr>
            <td>
                No Apto
            </td>
            <td>
                Significa el incumplimiento a los requerimientos de cualquiera de los exámenes. Este resultado excluye de forma definitiva al aspirante en el procedimiento de ingreso, hasta en tanto no se expida otra convocatoria.
            </td>
        </tr>
    </tbody>
    <tfoot>
    </tfoot>
</table>
<div class="row">
    <div class="bg-navy-active">
        <h5>Evaluaciones del Proceso de Selección</h5>
    </div>
</div>

<table id="tabla-seleccion" class="table table-bordered table-hover aspirante-tabla">
    <thead>
        <tr>
            <th>No</th>
            <th>Evaluación</th>
            <th>Fecha</th>
            <th>Observaciones</th>
            <th>Resultado</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php $contador = 1; ?>
        <?php foreach ( $aspirante->logSeleccion as $log ) { ?>
            <tr  requerimiento="<?= $log->id?>">
                <td><?php echo $contador++; ?></td>
                <td><?php echo $log->idSeleccion0->nombre; ?></td>
                <td><?php echo $log->fechaText; ?></td>
                <td><?php echo $log->observaciones; ?></td>
                <td class="dato_cumplimiento" class="dato_cumplimiento"><?php echo $log->resultados0->valor; ?></td>
                <td>
                    <a class="btn btn-block" data-toggle="modal" data-target="#modal-seleccion-<?= $log->id ?>">
                        <i data-toggle="tooltip" data-placement="left" title="Editar" class="glyphicon glyphicon-pencil"></i>
                    </a>
                </td>
            </tr>
        <?php } ?>
    </tbody>
    <tfoot>
    </tfoot>
</table>

<?php foreach ( $aspirante->logSeleccion as $log ) { ?>
    <div class="modal fade" id="modal-seleccion-<?= $log->id ?>" tabindex="-1" role="dialog" aria-labelledby="modal-seleccion-<?= $log->id ?>" aria-hidden="true">
        <div class="modal-dialog">
            <?php 
                $form = ActiveForm::begin([
                    'layout' => 'horizontal',
                    'enableClientValidation' => false,
                    'action'=>Yii::$app->urlManager->getBaseUrl() . '/log-seleccion/update?id=' . $log->id
                ]);
            ?>
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Edición de la evaluación: <?= $log->idSeleccion0->nombre ?></h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="form-group">
                            <label class="control-label col-sm-3">
                                Evaluación
                            </label>
                            <div class="col-sm-6">
                                <input class="modal-input-info" type="text" value="<?= $log->idSeleccion0->nombre; ?>">
                                <input type="hidden" id="logseleccion-idrechazo" class="form-control modal-input" name="LogSeleccion[idSeleccion]" value="<?= $log->idSeleccion ?>">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <label class="control-label col-sm-3">
                                Elemento
                            </label>
                            <div class="col-sm-6">
                                <input class="modal-input-info" type="text" value="<?= $aspirante->nombre . " " . $aspirante->apellido_paterno . " " . $aspirante->apellido_materno; ?>">
                                <input type="hidden" id="logseleccion-idelemento" class="form-control modal-input" name="LogSeleccion[idElemento]" value="<?= $log->idElemento ?>">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <label class="control-label col-sm-3">
                                Fecha
                            </label>
                            <div class="col-sm-6">
                                <input class="modal-input-info" type="date" value="<?= $log->fecha; ?>" id="logseleccion-fecha" name="LogSeleccion[fecha]">                                
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <?= $form->field($log, 'resultados')
                                 ->dropDownList(
                                    ArrayHelper::map(ResultadosSeleccion::find()->select('id, valor')
                                                                                ->all(), 'id', 'valor'),
                                    ['class'=>'modal-input'])
                                 ->label('Resultado');?>
                    </div>
                    <div class="row">
                        <?= $form->field($log, 'observaciones')
                                 ->textarea(['rows' => 6, 'class'=>'modal-input'])
                                 ->label('Observaciones') ?>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="hidden" id="logseleccion-idelemento" class="form-control modal-input" name="idElemento" value="<?= $aspirante->id ?>">
                    <button class="btn btn-primary modal-input"><i class="glyphicon glyphicon-floppy-disk"></i> Guardar</button>
                    <button class="btn btn-default modal-input" data-dismiss="modal"><i class="glyphicon glyphicon-repeat"></i> Cancelar</button>
                </div>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
<?php } ?>