models/LogLicencias.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "log_licencias".
 */
class LogLicencias extends \app\models\base\LogLicencias
{
}

controllers/LogLicenciasController.php
<?php

namespace app\controllers;

use Yii;
use app\models\LogLicencias;
use app\models\LogLicenciasSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\HttpException;
use yii\filters\AccessControl;
use yii\helpers\Url;
use app\models\FormSearch;
use app\models\Elementos;

/**
 * LogLicenciasController implements the CRUD actions for LogLicencias model.
 */
class LogLicenciasController extends Controller
{
	public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
            ],
        ];
    }

	/**
	 * Lists all LogLicencias models.
	 * @return mixed
	 */
	public function actionIndex($id)
	{
		Url::remember();
		$model = new LogLicencias();
		 try {
            if ($model->load($_POST) && $model->save()) {
            	$model = new LogLicencias();
            }
        } catch (\Exception $e) {
            $msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
            $model->addError('_exception', $msg);
        }

        $form     = new FormSearch;
        $elemento = Elementos::findOne($id);

		return $this->render('index', [
			'model' => $model,
            'form' => $form,
            'elemento' => $elemento
		]);
	}

	/**
	 * Displays a single LogLicencias model.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionView($id)
	{
        Url::remember();
        return $this->render('view', [
			'model' => $this->findModel($id),
		]);
	}

	/**
	 * Creates a new LogLicencias model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 * @return mixed
	 */
	public function actionCreate()
	{
		$model = new LogLicencias;

		try {
            if ($model->load($_POST) && $model->save()) {
                return $this->redirect(Url::previous());
            } elseif (!\Yii::$app->request->isPost) {
                $model->load($_GET);
            }
        } catch (\Exception $e) {
            $msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
            $model->addError('_exception', $msg);
		}
        return $this->render('create', ['model' => $model,]);
	}

	/**
	 * Updates an existing LogLicencias model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionUpdate($id)
	{
		$model = $this->findModel($id);
		if ($model->load($_POST) && $model->save()) {
            return $this->redirect(Url::previous());
		} else {
			return $this->renderAjax('update', [
				'model' => $model,
			]);
		}
	}

	/**
	 * Deletes an existing LogLicencias model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionDelete($id, $idElemento)
	{
		$this->findModel($id)->delete();
		return $this->redirect(['index?id=' . $idElemento]);
	}

	/**
	 * Finds the LogLicencias model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 * @param integer $id
	 * @return LogLicencias the loaded model
	 * @throws HttpException if the model cannot be found
	 */
	protected function findModel($id)
	{
		if (($model = LogLicencias::findOne($id)) !== null) {
			return $model;
		} else {
			throw new HttpException(404, 'The requested page does not exist.');
		}
	}
}

views/log-licencias/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Licencias;
use yii\helpers\Url;

/**
* @var yii\web\View $this
* @var app\models\LogLicencias $model
* @var yii\widgets\ActiveForm $form
*/
$cssButton = $model->isNewRecord ? "btn btn-app" : "btn btn-app hidden";
?>

<div class="log-licencias-form">

    <?php $form = ActiveForm::begin(['layout' => 'horizontal', 'enableClientValidation' => true, 'id' => 'form-log']); ?>

     <div class="row">
        <?php echo $form->errorSummary($model, ['header' => 'Por favor corrija los errores:']); ?>
    </div>
    <div class="">
        <ul id="w0" class="nav nav-tabs"><li class="active"><a href="#w0-tab0" data-toggle="tab">Licencias</a></li></ul>

        <p>
            
			<?= $form->field($model->idElemento0, 'nombreText')->label('Nombre del elemento')->textInput(['readonly' => true]) ?>
			<?= $form->field($model, 'idLicencia')
                ->label('Tipo de Evento')
                ->dropDownList(
                    ArrayHelper::map(Licencias::find()->all(), 'id', 'tipo')
                )
            ?>
			<?= $form->field($model, 'fecha_insercion')->label('Fecha de Iserción')->textInput(['type' => 'date', 'disabled' => '']); ?>
			<?= $form->field($model, 'fecha_inicio')->label('Inicio del Evento')->textInput(['type' => 'date']); ?>
			<?= $form->field($model, 'fecha_fin')->label('Fin del Evento')->textInput(['type' => 'date']); ?>
			<?= $form->field($model, 'motivo')->textarea(['rows' => 6]) ?>
			<?= $form->field($model, 'observaciones')->textarea(['rows' => 6]) ?>
        </p>
        <hr/>

        <?= Html::submitButton('<span class="fa fa-save"></span> '.'Guardar', ['class' => $cssButton]) ?>
        <a href="<?php echo Url::previous(); ?>" class="<?php echo $cssButton ?>">
            <i class="fa fa-times"></i>Cancelar
        </a>
        <?php ActiveForm::end(); ?>

    </div>

</div>

views/log-licencias/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var app\models\LogLicenciasSearch $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="log-licencias-search">

	<?php $form = ActiveForm::begin([
		'action' => ['index'],
		'method' => 'get',
	]); ?>

		<?= $form->field($model, 'id') ?>

		<?= $form->field($model, 'idElemento') ?>

		<?= $form->field($model, 'idLicencia') ?>

		<?= $form->field($model, 'motivo') ?>

		<?= $form->field($model, 'fecha_insercion') ?>

		<?php // echo $form->field($model, 'fecha_inicio') ?>

		<?php // echo $form->field($model, 'fecha_duracion') ?>

		<?php // echo $form->field($model, 'observaciones') ?>

		<div class="form-group">
			<?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
			<?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
		</div>

	<?php ActiveForm::end(); ?>

</div>

views/log-licencias/create.php
<?php

use yii\helpers\Html;

/**
* @var yii\web\View $this
* @var app\models\LogLicencias $model
*/

$this->title = 'Create';
$this->params['breadcrumbs'][] = ['label' => 'Log Licencias', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="log-licencias-create">

    <p class="pull-left">
        <?= Html::a('Cancel', \yii\helpers\Url::previous(), ['class' => 'btn btn-default']) ?>
    </p>
    <div class="clearfix"></div>

    <?php echo $this->render('_form', [
    'model' => $model,
    ]); ?>

</div>

views/log-licencias/index.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Licencias;

/**
* @var yii\web\View $this
* @var yii\data\ActiveDataProvider $dataProvider
* @var app\models\LogLicenciasSearch $searchModel
*/
$this->registerJsFile(Yii::$app->homeUrl.'js/datatables/tablas.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerCssFile(Yii::$app->homeUrl . '/css/activos/planes.css');
$urlIndex = Url::to(['licencias/']);
$this->title = 'Licencias';
$blockName = 'licencias';
?>

<section class="content-header">

    <h1>
        <?php echo $this->title; ?>
        <small></small>
    </h1>

    <ol class="breadcrumb">
        <li><a href="<?php echo Yii::$app->homeUrl; ?>"><i class="fa fa-home"></i> Inicio</a></li>
        <li class="active"><?php echo $this->title; ?></li>
    </ol>

</section>

<section class="content">
    <div class="box box-primary">
        <div class="box-header">
            <?= $this->render('//planes/formacion_header', ['elemento' => $elemento]); ?>
        </div>
        <div class="box-body">
            <div class="bg-navy-active">
                <h5>Agregar una nueva licencia, permiso, comisión o incapacidad</h5>
            </div>
            <?php $form = ActiveForm::begin([
                'action' => Url::to(['log-licencias/', 'id' => $elemento->id]),
                'method' => 'post',
                'enableClientValidation' => true]);
            ?>
            <div class="row">
                <?php echo $form->errorSummary($model, ['header' => 'Por favor corrija los errores:']); ?>
            </div>
            <div>
                <?php $this->beginBlock($blockName); ?>
                <div class="row">
                    <div class="col-md-3">
                        <?= $form->field($model, 'idLicencia')
                            ->label('Tipo de Evento')
                            ->dropDownList(
                                ArrayHelper::map(Licencias::find()->all(), 'id', 'tipo')
                            )
                        ?>
                    </div>
                    <div class="col-md-3">  
                        <?= $form->field($model, 'fecha_insercion')->label('Fecha de Iserción')->textInput(['type' => 'date', 'readonly' => 'true', 'value' => date('Y-m-d', time())]); ?>
                    </div>
                    <div class="col-md-3">  
                        <?= $form->field($model, 'fecha_inicio')->label('Inicio del Evento')->textInput(['type' => 'date']); ?>
                    </div>
                    <div class="col-md-3">  
                        <?= $form->field($model, 'fecha_fin')->label('Fin del Evento')->textInput(['type' => 'date']); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <?= $form->field($model, 'motivo')->label('Concepto')->textInput(); ?>
                    </div>
                    <div class="col-md-9">
                        <?= $form->field($model, 'observaciones')->label('observaciones')->textarea(); ?>
                    </div>
                    <div class="col-md-2">
                        <label class="control-label"></label>
                        <span class="">
                            <?php echo Html::submitButton('', ['class' => 'btn btn-info btn-block fa fa-plus-circle']); ?>
                        </span>
                        <?= $form->field($model, 'idElemento')->label(false)->textInput(['type' => 'hidden', 'value' => $elemento->id]); ?>
                    </div>
                </div>
                <?php $this->endBlock(); ?>
                <?php ActiveForm::end(); ?>
                <p>
                    <?= $this->blocks[$blockName]; ?>
                </p>
            </div>
            <h4>Histórico de Incapacidades, Licencias, Permisos y Comisiones</h4>
            <?= $this->render('@app/views/layouts/modal', []); ?>
            <div class="bg-navy-active">
                <h5>Histórico de Incapacidades, Licencias, Permisos y Comisiones</h5>
            </div>
            <table id="resultados" class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Tipo de Evento</th>
                        <th>Motivo</th>
                        <th>Fecha de Inserción</th>
                        <th>Inicio de Evento</th>
                        <th>Fin de Evento</th>
                        <th>Observaciones</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php $contador = 1; ?>
                    <?php foreach ( $elemento->logLicencias as $log ) { ?>
                        <tr>
                            <td><?php echo $contador++; ?></td>
                            <td><?php echo $log->idLicencia0->tipo; ?></td>
                            <td><?php echo $log->motivo; ?></td>
                            <td><?php echo $log->fecha_insercion; ?></td>
                            <td><?php echo $log->fecha_inicio; ?></td>
                            <td><?php echo $log->fecha_fin; ?></td>
                            <td><?php echo $log->observaciones; ?></td>
                            <td>
                                <a class="btn btn-block" data-toggle="modal" data-target="#modal-model" data-modal-type="edit" data-action="<?php echo Url::to(['log-licencias/update', 'id' => $log->id]) ?>">
                                    <span data-toggle="tooltip" data-placement="left" title="Editar" class="glyphicon glyphicon-pencil"></span>
                                </a>
                            </td>
                            <td>
                                <a class="btn btn-block" data-toggle="modal" data-target="#modal-model" data-modal-type="remove" data-action="<?php echo Url::to(['log-licencias/delete', 'id' => $log->id, 'idElemento'=>$elemento->id]) ?>">
                                    <span data-toggle="tooltip" data-placement="left" title="Eliminar" class="glyphicon glyphicon-trash"></span>
                                </a>
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
                <tfoot>
                </tfoot>
            </table>
        </div>
        <div class="box-footer">
            <a style="visibility:show" href="<?php echo $urlIndex; ?>" class="btn btn-app">
                <i class="fa fa-arrow-left"></i>Regresar
            </a>
        </div>
    </div>
</div>

views/log-licencias/update.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\models\LogLicencias $model
 */

$this->title = 'Actualiza Licencia ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Log Licencias', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Actualiza';
?>
<div class="log-licencias-update">

	<?php echo $this->render('_form', [
		'model' => $model,
	]); ?>

</div>

views/log-licencias/view.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;

/**
* @var yii\web\View $this
* @var app\models\LogLicencias $model
*/

$this->title = 'Log Licencias View ' . $model->id . '';
$this->params['breadcrumbs'][] = ['label' => 'Log Licencias', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="log-licencias-view">

    <p class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> Edit', ['update', 'id' => $model->id],
        ['class' => 'btn btn-info']) ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> New Log Licencias', ['create'], ['class' => 'btn
        btn-success']) ?>
    </p>

        <p class='pull-right'>
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> List', ['index'], ['class'=>'btn btn-default']) ?>
    </p><div class='clearfix'></div> 

    
    <h3>
        <?= $model->id ?>    </h3>


    <?php $this->beginBlock('app\models\LogLicencias'); ?>

    <?php echo DetailView::widget([
    'model' => $model,
    'attributes' => [
    			'id',
			'idElemento',
			'idLicencia',
			'motivo:ntext',
			'fecha_insercion',
			'fecha_inicio',
			'fecha_duracion',
			'observaciones:ntext',
    ],
    ]); ?>

    <hr/>

    <?php echo Html::a('<span class="glyphicon glyphicon-trash"></span> Delete', ['delete', 'id' => $model->id],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => Yii::t('app', 'Are you sure to delete this item?'),
    'data-method' => 'post',
    ]); ?>

    <?php $this->endBlock(); ?>


    
    <?=
    \yii\bootstrap\Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [ [
    'label'   => '<span class="glyphicon glyphicon-asterisk"></span> LogLicencias',
    'content' => $this->blocks['app\models\LogLicencias'],
    'active'  => true,
], ]
                 ]
    );
    ?></div>